const NAME_OR_PASSWORD_OR_TYPE_IS_NOT_EXIST = "NAME_OR_PASSWORD_OR_TYPE_IS_NOT_EXIST"
const USER_IS_EXIST = "USER_IS_EXIST"
const USER_IS_NOT_EXIST = "USER_IS_NOT_EXIST"
const PASSWORD_IS_WRONG = "PASSWORD_IS_WRONG"
const UNAUTHORIZATION = "UNAUTHORIZATION"
const UNPEIMISSION = "UNPEIMISSION"
const AVATAR_UPLOAD_FAILURE = "AVATAR_UPLOAD_FAILURE"
const PASSWORD_IS_NONSTANDARD = "PASSWORD_IS_NONSTANDARD"
const SEND_ERROR = "SEND_ERROR"
const QUERY_ERROR = "QUERY_ERROR"
const FILE_FORMAT_UPLOAD_ERROR = "FILE_FORMAT_UPLOAD_ERROR"
const NETWORK_ERROR = "NETWORK_ERROR"
const FILE_FORMAT_IMPORT_ERROR = "FILE_FORMAT_IMPORT_ERROR"
const TABLE_DATA_FORMAT_ERROR = "TABLE_DATA_FORMAT_ERROR"
const CANT_DELETE_MANAGER = "CANT_DELETE_MANAGER"
const FIELD_CANT_NONE = "FIELD_CANT_NONE"
const DATA_IS_NOT_EXIST = "DATA_IS_NOT_EXIST"

module.exports = {
  NAME_OR_PASSWORD_OR_TYPE_IS_NOT_EXIST,
  USER_IS_NOT_EXIST,
  USER_IS_EXIST,
  PASSWORD_IS_WRONG,
  UNAUTHORIZATION,
  UNPEIMISSION,
  AVATAR_UPLOAD_FAILURE,
  PASSWORD_IS_NONSTANDARD,
  SEND_ERROR,
  QUERY_ERROR,
  FILE_FORMAT_UPLOAD_ERROR,
  NETWORK_ERROR,
  FILE_FORMAT_IMPORT_ERROR,
  TABLE_DATA_FORMAT_ERROR,
  CANT_DELETE_MANAGER,
  FIELD_CANT_NONE,
  DATA_IS_NOT_EXIST
}